### PR TITLE
Fix for issue #10: Namespace ambiguity issue for filesystem mount point part of metrics

### LINKED ISSUE #10: Namespace ambiguity issue for filesystem mount point part of metrics
Due to the fact that the filesystem part of the "df -T -P" output might contain / like the following output coming from my Linux system

```C
Filesystem                Type     1024-blocks      Used Available Capacity Mounted on
udev                      devtmpfs     8113640        12   8113628       1% /dev
tmpfs                     tmpfs        1624944      2524   1622420       1% /run
/dev/dm-3                 ext4       103077152  84200980  13617116      87% /
none                      tmpfs              4         0         4       0% /sys/fs/cgroup
none                      tmpfs           5120         0      5120       0% /run/lock
none                      tmpfs        8124712       280   8124432       1% /run/shm
none                      tmpfs         102400        32    102368       1% /run/user
/dev/mapper/data--vg-data ext4       722343000 319310640 371560244      47% /data
/dev/sda1                 ext4         1998672    393128   1484304      21% /boot
/dev/mapper/vms--vg-vms   ext4       309501952 151700240 142056896      52% /vms
```

The plugin code internally converts these chars into _ using the [following code](https://github.com/intelsdi-x/snap-plugin-collector-df/blob/master/df/plugin.go#L220)

Doing this, there is no way (or at least there does not seem to be at first look) for the user to be able to differentiate between /dir1/part1 and /dir1_part1

### PR DESCRIPTION
**Pull request by obourdon**
Fixes #10 
Add configurable option for keeping unchanged mountpoints in returned metrics

Summary of changes:
- add configurable option
- tests modified accordingly

How to verify it:
- activating the option and passing data to heka publisher and looking into grafana just work perfectly

Testing done:
- small & legacy test passed

### CODE REVIEW

**Comment by obourdon** [comment]
cc: [@intelsdi-x/plugin-maintainers](https://github.com/orgs/intelsdi-x/teams/plugin-maintainers)
@jcooklin 

Could you please have a look.

File: df/plugin.go [hunk 1]
```diff
@@ -412,14 +422,18 @@ func (dfs *dfStats) collect(procPath string, excluded_fs_names []string, exclude
 		dfm.Filesystem = rightFields[1]
 		dfm.FsType = rightFields[0]
 		dfm.UnchangedMountPoint = leftFields[4]
-		if leftFields[4] == "/" {
-			dfm.MountPoint = "rootfs"
+		if keep_original_mountpoint {
```
Comment (jcooklin) [inline df/plugin.go]: I thought the default behavior would have kept the original mount point now that the framework supports namespace elements containing `/` characters.  

Was this an effort to be conservative?  

I'd be inclined to change the behavior to keep the original mount point (and not provide an option preserving the old behavior) or at least make the default behavior preserve the  mount point.

File: df/plugin.go [hunk 2]
```diff
@@ -310,10 +316,12 @@ func (p *dfCollector) GetConfigPolicy() (*cpolicy.ConfigPolicy, error) {
...
-	rule, _ = cpolicy.NewStringRule(ExcludedFSNames, false, strings.Join(dfltExcludedFSNames, ","))
-	node.Add(rule)
-	rule, _ = cpolicy.NewStringRule(ExcludedFSTypes, false, strings.Join(dfltExcludedFSTypes, ","))
-	node.Add(rule)
+	rule1, _ := cpolicy.NewStringRule(ExcludedFSNames, false, strings.Join(dfltExcludedFSNames, ","))
+	node.Add(rule1)
+	rule2, _ := cpolicy.NewStringRule(ExcludedFSTypes, false, strings.Join(dfltExcludedFSTypes, ","))
+	node.Add(rule2)
+	rule3, _ := cpolicy.NewBoolRule(KeepOriginalMountPoint, false, false)
+	node.Add(rule3)
```
Comment (jcooklin) [inline df/plugin.go]: The readme should be updated to describe this new option.

File: df/plugin.go (hunk 1 above)
Comment (obourdon) [inline df/plugin.go]: @jcooklin This was definitely done on purpose to be conservative with default behaviour. However I would be very happy to change this and make the default behaviour now be to keep the original mount point
New PR version will follow accordingly

**Comment by obourdon** [comment]
@jcooklin could you please review latest PR revision which should now comply to your requested changes. Thanks
